### ISSUE TITLE
AUR Package?

### ISSUE THREAD

**Issue by ZakharH** [supremesonicbrazil/SLSK#12]
Would be nice for a one-step install for arch users. It would also help greatly to make sure we are always running with the latest database.

**Comment by supremesonicbrazil** [comment]
I use Antergos myself (although not at this moment) so you can bet I'll be looking into that ;)

I'll put it in TODO.md to make sure I won't forget, thanks for the suggestion!

**Comment by supremesonicbrazil** [comment]
Hey sorry for the delay, I managed to create a PKGBUILD and, from what I've tested, seems to be working fine. I've yet to submit it for revision for the Arch community after v1.3.0.0 is merged successfully to the `master` branch (due to what I've stated in issue #13 ), but once this is sorted out I'll be sure to let ya know :)

**Comment by supremesonicbrazil** [comment]
Sorry to keep you waiting, I've updated the README file today and SLSK is now available in the AUR! Package name is `slsk-git`, feel free to use it ;)
