### ISSUE TITLE
Linker error 1.3.0.x

### ISSUE THREAD

**Issue by malkavi** [supremesonicbrazil/SLSK#16]
I'm trying to create a package for OpenSuse and since version 1.3.0 I'm having an error:
```
[   73s] g++ -c -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I../src -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o moc_progressmenu.o moc_progressmenu.cpp
[   74s] g++ -Wl,-O1 -o SteamLinuxSwissKnife main.o mainwindow.o mainmenu.o db.o sqlite3.o progressmenu.o moc_mainwindow.o moc_progressmenu.o   -ldl -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5Core -lGL -lpthread 
[   75s] progressmenu.o:(.bss+0x50): multiple definition of `CurrentConfig'
[   75s] mainmenu.o:(.bss+0x20): first defined here
[   75s] /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: Warning: size of symbol `CurrentConfig' changed from 8 in mainmenu.o to 24 in progressmenu.o
[   75s] progressmenu.o:(.bss+0x70): multiple definition of `CurrentSave'
[   75s] mainmenu.o:(.bss+0x28): first defined here
[   75s] /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: Warning: size of symbol `CurrentSave' changed from 8 in mainmenu.o to 24 in progressmenu.o
[   75s] collect2: error: ld returned 1 exit status
[   75s] Makefile:142: recipe for target 'SteamLinuxSwissKnife' failed
[   75s] make: *** [SteamLinuxSwissKnife] Error 1
[   75s] error: Bad exit status from /var/tmp/rpm-tmp.pWdmXc (%build)
```
The error seems to be that those variables are by default 'externals'. (not sure, but making static the variables the error is gone) (Qt version 5,6)
I'm using the OpenSuse build service, you can use it for different linux dist.
The URL of the package:
https://build.opensuse.org/package/show/home:malkavi/SLSK

**Comment by supremesonicbrazil** [comment]
Hmm, interesting. I've checked here and I noticed mainmenu.cpp and progressmenu.cpp each have their own CurrentSave and CurrentConfig variables, but their types differ - mainmenu.cpp has normal strings, progressmenu.cpp has string vectors. So if we think about it there really were multiple definitions, and I guess OpenSUSE's build service gets really confused with things like this. I'm not familiar with OpenSuse neither its build service (is it like the AUR?) but I think this might be the case.

Since making those variables static in one of the files did solve the issue, I've made those variables static in both files, each in their own namespace, just to be sure. If you wanna give it a shot, it's already there in the `dev` branch.

**Comment by malkavi** [comment]
Thanks.
I have created another package SLSK-dev and is working using github dev branch. You can add to the README or clone the repo or whatever you want! ;)
Packages:
https://build.opensuse.org/package/show/home:malkavi/SLSK
https://build.opensuse.org/package/show/home:malkavi/SLSK-dev  (directly from github)
Install/Instructions from OpenSuse:
https://software.opensuse.org//download.html?project=home%3Amalkavi&package=SLSK

**Comment by supremesonicbrazil** [comment]
Thanks a lot! I've added links to both packages in the README in the `dev` branch, I guess I did it right I think.

Don't worry about the `master` branch for now even if it technically is not fixed, I'll merge the `dev` branch next Sunday, or if it's completely urgent for the package to work, I'll try to merge ASAP, just let me know ;)

**Comment by malkavi** [comment]
We can wait till sunday. Thanks
