### ISSUE TITLE
$STEAMAPPS hardcoded path issue.

### ISSUE THREAD

**Issue by notexe** [supremesonicbrazil/SLSK#3]
Hello,
`$STEAMAPPS` is hardcoded to `~/.local/share/Steam/steamapps/common/` which doesn't work on my system because I store all my games on a secondary hard drive in my computer.

I suggest parsing the file `libraryfolders.vdf` located in `~/.local/share/Steam/steamapps/` so the program can search through all the different Steam library paths. This is an example of what the file looks like:

```
"LibraryFolders"
{
	"TimeNextStatsReport"		"1513211018"
	"ContentStatsID"		"8390577854283445701"
	"1"		"/mnt/storage/Games/Steam"
}
```

Thanks.

**Comment by supremesonicbrazil** [comment]
Hmm, right. I need a refresher, I never used secondary HDDs to store my Steam games (in fact I even copied my own `libraryfolders.vdf` for consulting and the last line isn't there, guess it's because of that). I don't remember if Steam lets you have more than two library paths *at the same time*, like, is there a limit?

You actually gave me an idea regarding this: I think there might be another way to do this as well, like, there could be an entry for your desired library's path above the backup folder entry in the GUI tool (like "origin" and "destination", get it?). Does every Steam library path spawn a `libraryfolder.vcf` regardless of how your library categories are set up? We could make it scan the folder for it, and if it exists, it means it's a Steam library folder, so we could make the GUI tool iterate from there like it iterates through the backup folder.

**Comment by notexe** [comment]
I don't think there is any limit of how many library paths you can have. The structure of the library paths are exactly the same as the one in Steam's installation folder. There doesn't appear to be a `libraryfolders.vdf` file in other libraries, only seems to be in the default library folder.

**Comment by supremesonicbrazil** [comment]
Oh right, so we have a `common` folder and pretty much everything else inside except for the `libraryfolder.vdf`, right?

In that case, I'll do some quick changes here and push them to a dev branch if you wanna test. If it's all good I'll merge it with the main.

**Comment by notexe** [comment]
Yep that is correct.

**Comment by supremesonicbrazil** [comment]
@notexe When searching for the games folder, choose your `common` folder in your secondary HDD's Steam library and give it a shot. I think this might work, but I haven't tested it myself because I still don't have that much access to my own HDD.

**Comment by notexe** [comment]
Seems to work fine. Had trouble backing up the configuration for Super Crate Box though, but I think that may be an error I made when adding it into the database.

It does find all my games though and I can backup all of them fine.

**Comment by supremesonicbrazil** [comment]
Nice! :smile:

Feel free to keep experimenting with it and add any more details, I'll finish some other things here before I merge.

**Comment by supremesonicbrazil** [comment]
Dev branch has been merged, thanks a lot for the feedback! :smiley:
