### ISSUE TITLE
Bad values in DB.csv's SaveFolder and ConfigFolder columns

### ISSUE THREAD

**Issue by vetleledaal** [supremesonicbrazil/SLSK#33]
For a SaveFolder or ConfigFolder value to be valid, I would assume it should be either to the left or right of the last forward slash in the *Path column.

I listed out the inconsistencies here:
```cpp
// AppID: 251570, ConfigFolder1
"7 Days to Die" != "The Fun Pimps"
"7 Days to Die" != "7 Days To Die"

// AppID: 508230, ConfigFolder2
"~/.renpy/Anime Studio Simulator-1463664611" != "Anime Studio Simulator-1463664611"
"~/.renpy/Anime Studio Simulator-1463664611" != "persistent"

// AppID: 233550, SaveFolder1
"AnotherWorld" != "DotEMU"
"AnotherWorld" != "Another World"

// AppID: 233550, ConfigFolder1
"AnotherWorld" != "DotEMU"
"AnotherWorld" != "Another World"

// AppID: 671700, SaveFolder1
"Dead Horizon" != "14HoursProductions"
"Dead Horizon" != "DeadHorizon"

// AppID: 671700, ConfigFolder1
"Dead Horizon" != "DeadHorizon"
"Dead Horizon" != "prefs"

// AppID: 227300, ConfigFolder1
"Euro Truck Simulator" != "Euro Truck Simulator 2"
"Euro Truck Simulator" != "config.cfg"

// AppID: 70, SaveFolder1
"valve/SAVE" != "valve"
"valve/SAVE" != "SAVE"

// AppID: 220, SaveFolder1
"hl2/save" != "hl2"
"hl2/save" != "save"

// AppID: 220, ConfigFolder1
"hl2/cfg" != "hl2"
"hl2/cfg" != "cfg"

// AppID: 380, SaveFolder1
"episodic/save" != "episodic"
"episodic/save" != "save"

// AppID: 380, ConfigFolder1
"episodic/cfg" != "episodic"
"episodic/cfg" != "cfg"

// AppID: 420, SaveFolder1
"ep2/save" != "ep2"
"ep2/save" != "save"

// AppID: 420, ConfigFolder1
"ep2/cfg" != "ep2"
"ep2/cfg" != "cfg"

// AppID: 340, SaveFolder1
"lostcoast/save" != "lostcoast"
"lostcoast/save" != "save"

// AppID: 340, ConfigFolder1
"lostcoast/cfg" != "lostcoast"
"lostcoast/cfg" != "cfg"

// AppID: 130, SaveFolder1
"bshift/SAVE" != "bshift"
"bshift/SAVE" != "SAVE"

// AppID: 50, SaveFolder1
"gearbox/SAVE" != "gearbox"
"gearbox/SAVE" != "SAVE"

// AppID: 280, SaveFolder1
"hl1/save" != "hl1"
"hl1/save" != "save"

// AppID: 280, ConfigFolder1
"hl1/cfg" != "hl1"
"hl1/cfg" != "cfg"

// AppID: 451760, ConfigFolder1
"~/.renpy/Highway Blossoms-1445311445" != "Highway Blossoms-1445311445"
"~/.renpy/Highway Blossoms-1445311445" != "persistent"

// AppID: 355970, ConfigFolder1
"Home is Where One Starts…" != "Home is Where One Starts..."
"Home is Where One Starts…" != "prefs"

// AppID: 230700, ConfigFolder1
"La-mulana" != "la-mulana"
"La-mulana" != "config.ini"

// AppID: 108200, SaveFolder1
"Ticket to Ride" != "~"
"Ticket to Ride" != ".Ticket to Ride"

// AppID: 108200, ConfigFolder1
"Ticket to Ride" != "~"
"Ticket to Ride" != ".Ticket to Ride"
```

**Comment by supremesonicbrazil** [comment]
Hey thanks a lot, should be fixed now in the `dev` branch. And sorry for that, sometimes these little details go unnoticed really easy =P

About all the Half-Life titles, they're actually like this on purpose for a special reason, which I've written about in [CONTRIBUTING.md](https://github.com/supremesonicbrazil/SLSK/blob/master/CONTRIBUTING.md#guidelines-for-adding-entries), in the Path Structures section under Guidelines for adding entries (it's kinda hidden there at the footnotes):

`In the rare event that there's two or more different games writing saves/configs in the same folder (such as Half-Life 2 and its Episodes), prepend the previous folder in Save/ConfigFolder - like "hl2/save", "episodic/save" and "ep2/save" instad of just "save" - to avoid overwriting`

For now they seem to be the only exception to the rule, since they all are actually based just on Half-Life and Half-Life 2, each one in their own sub-folder.

Also, you've got a good eye there in "Home is Where One Starts...", I can barely see any difference in the "..." even after changing it to the right thing in the spreadsheet (I had to copy-paste the SavePath/SaveFolder to make sure it was right), I could only notice it now when you've shown them side-by-side. Not sure if it's my PC's fonts or anything, but I guess that's fixed too now :open_mouth:
